### ISSUE TITLE
Appveyor build failure: certificate verify failed

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#22]
Windows build fails in Appveyor because of this:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
      	C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
      	C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
      	C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
      	C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
      	C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1398:in `request'
      	C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1156:in `get'
      	C:/projects/sibit/lib/sibit.rb:205:in `get_json'
      	C:/projects/sibit/lib/sibit.rb:119:in `balance'
```

It seems to be the problem explained here: https://help.appveyor.com/discussions/problems/2196-openssl-certificate-verify-failed-when-trying-to-connect-to-ciappveyorcom

This may also help: https://stackoverflow.com/questions/5720484/how-to-solve-certificate-verify-failed-on-windows

**Comment by mtuktarov** [comment]
I've submitted a PR https://github.com/yegor256/sibit/pull/29
But it appears that there is something else.
Unfortunately, I don't know Ruby

**Comment by mtuktarov** [comment]
```
  Scenario: Bitcoin transaction can be sent                                                                                                                                                                                            # features\cli.feature:33
    When I run bin/sibit with "--verbose --dry pay 100000 S 1JvCsJtLmCxEk7ddZFnVkGXpr9uhxZPmJi:fd2333686f49d8647e1ce8d5ef39c304520b08f3c756b67068b30a3db217dcb2 1JvCsJtLmCxEk7ddZFnVkGXpr9uhxZPmJi 1JvCsJtLmCxEk7ddZFnVkGXpr9uhxZPmJi" # features/step_definitions/steps.rb:52
    Then Exit code is zero                                                                                                                                                                                                             # features/step_definitions/steps.rb:66
      Non-zero exit 255:
      GET /ticker: 200/2309b in 1235ms
      Sibit::Error: Failed to retrieve /unspent?active=1JvCsJtLmCxEk7ddZFnVkGXpr9uhxZPmJi&limit=1000 (500): No free outputs to spend
      	C:/projects/sibit/lib/sibit.rb:241:in `get_json'
      	C:/projects/sibit/lib/sibit.rb:321:in `size_of'
      	C:/projects/sibit/lib/sibit.rb:170:in `pay'
      	C:/projects/sibit/features/step_definitions/../../bin/sibit:98:in `<main>'
       (RuntimeError)
      features\cli.feature:35:in `Then Exit code is zero'
```

**Comment by yegor256** [comment]
@mtuktarov it seems that someone stole the bitcoins I created for testing :(

**Comment by yegor256** [comment]
fixed

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#22` is not assigned, can't get performer
