### ISSUE TITLE
ERROR: NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#27]
```
ERROR: NoMethodError: undefined method `+' for nil:NilClass
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.12.1/lib/sibit.rb:304:in `rescue in post_tx'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.12.1/lib/sibit.rb:291:in `post_tx'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.12.1/lib/sibit.rb:215:in `pay'
	/app/objects/assets.rb:195:in `pay'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.2`
