### ISSUE TITLE
negative fee

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#28]
```
INFO: A new Bitcoin transaction c65c71eec275bc4ccd9a1777156d7434130a6e867cb2973cca0a121f210c0fda prepared:
  2 inputs:
     in: 5632e4b7e781393c45a08bf1f91e7ed18151b2cd3796fc326bfec7ccb7d0944d:1
     in: 59efe40f631bfae5b1baceca828111497b31ae359acd42705eb9e63432768927:1
  2 outputs:
    out: 76a91402251ee8a2e47b661c6e53a5b261d2f177499fa888ac / 1,901,088s/$165.74
    out: 76a9145d5b8b33a736a328c5153cb79a00b6d87adb20a388ac / 9,297,109s/$810.53
  Min tx fee: 10,000s/$0.87
  Fee left: -100,160s/$-8.73
  Tx size: 460 bytes
  Unspent: 11,098,037s/$967.53
  Amount: 1,901,088s/$165.74
  Target address: 1CLpaWPRoHTH6dxGhWfWW8V3mqpQnsM98
  Change address is 19WdWQtrrqapbiFfjF65mvR1pYpXqDBQ27
ERROR: Sibit::Error: Failed to post tx to /pushtx: 500
Validation Error: BitcoindException(super=com.neemre.btcdcli4j.core.BitcoindException: Error #-26: 66: min relay fee not met, code=-26)
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.12.2/lib/sibit.rb:302:in `post_tx'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.12.2/lib/sibit.rb:215:in `pay'
	/app/objects/assets.rb:195:in `pay'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.3`
