### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass in btc.rb:61:in `balance'

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#69]
```
NoMethodError: undefined method `[]' for nil:NilClass in btc.rb:61:in `balance'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#69` is not assigned, can't get performer
