### ISSUE TITLE
NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#72]
```
NoMethodError: undefined method `map' for nil:NilClass
2020-08-13T19:40:31.261103189Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.0/lib/sibit/btc.rb:178:in `block in txns'
2020-08-13T19:40:31.261111093Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.0/lib/sibit/btc.rb:175:in `loop'
2020-08-13T19:40:31.261117837Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.0/lib/sibit/btc.rb:175:in `txns'
2020-08-13T19:40:31.261124249Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.0/lib/sibit/btc.rb:165:in `block'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#72` is not assigned, can't get performer
