### ISSUE TITLE
btc.rb: NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#73]
```
NoMethodError: undefined method `each' for nil:NilClass
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/btc.rb:127:in `block in utxos'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/btc.rb:121:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/btc.rb:121:in `utxos'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable_proxy-1.0.2/lib/retriable_proxy.rb:34:in `public_send'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable_proxy-1.0.2/lib/retriable_proxy.rb:34:in `block in method_missing'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable_proxy-1.0.2/lib/retriable_proxy.rb:43:in `block in __retrying'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable_proxy-1.0.2/lib/retriable_proxy.rb:43:in `__retrying'
	/app/vendor/bundle/ruby/2.6.0/gems/retriable_proxy-1.0.2/lib/retriable_proxy.rb:34:in `method_missing'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/bestof.rb:78:in `block in utxos'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/bestof.rb:108:in `block in best_of'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/bestof.rb:106:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/bestof.rb:106:in `best_of'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit/bestof.rb:77:in `utxos'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.1/lib/sibit.rb:119:in `pay'
	/app/objects/assets.rb:183:in `pay'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:45:in `block in method_missing'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/syncem-0.1.2/lib/syncem.rb:43:in `method_missing'
	/app/front/front_btc.rb:412:in `block (2 levels) in <top (required)>'
	/app/front/front_jobs.rb:49:in `block in job'
	/app/objects/update_job.rb:47:in `call'
	/app/objects/tracked_job.rb:34:in `call'
	/app/objects/safe_job.rb:37:in `call'
	/app/objects/exclusive_job.rb:35:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/exclusive_job.rb:34:in `call'
	/app/objects/async_job.rb:44:in `block (2 levels) in call'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `open_synchronized'
	/app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in `open'
	/app/objects/async_job.rb:43:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.2`

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#73` is not assigned, can't get performer
