### ISSUE TITLE
read timeout

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#74]
```
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
2020-09-08T17:23:53.526318989Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'
2020-09-08T17:23:53.526326760Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:159:in `read'
2020-09-08T17:23:53.526333671Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http/response.rb:324:in `ensure in read_chunked'
2020-09-08T17:23:53.526340362Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http/response.rb:324:in `read_chunked'
2020-09-08T17:23:53.526347032Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http/response.rb:285:in `block in read_body_0'
2020-09-08T17:23:53.526354035Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http/response.rb:253:in `inflater'
2020-09-08T17:23:53.526360760Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http/response.rb:283:in `read_body_0'
2020-09-08T17:23:53.526367495Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http/response.rb:204:in `read_body'
2020-09-08T17:23:53.526374128Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1229:in `block in get'
2020-09-08T17:23:53.526380701Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1518:in `block in transport_request'
2020-09-08T17:23:53.526387376Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http/response.rb:165:in `reading_body'
2020-09-08T17:23:53.526393983Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1517:in `transport_request'
2020-09-08T17:23:53.526416502Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1479:in `request'
2020-09-08T17:23:53.526424611Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
2020-09-08T17:23:53.526430685Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:920:in `start'
2020-09-08T17:23:53.526436558Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1470:in `request'
2020-09-08T17:23:53.526442482Z app[web.1]:    	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1228:in `get'
2020-09-08T17:23:53.526448403Z app[web.1]:    	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.20.2/lib/sibit/json.rb:53:in `get'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#74` is not assigned, can't get performer
