### ISSUE TITLE
unparseable JSON

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#82]
```
JSON::ParserError: 785: unexpected token at 'Don't abuse the API. Please contact webmaster@btc.com
'
	/app/vendor/bundle/ruby/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
	/app/vendor/bundle/ruby/2.6.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.21.4/lib/sibit/json.rb:67:in `get'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.21.4/lib/sibit/btc.rb:132:in `block (2 levels) in utxos'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.21.4/lib/sibit/btc.rb:131:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.21.4/lib/sibit/btc.rb:131:in `block in utxos'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.21.4/lib/sibit/btc.rb:123:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/sibit-0.21.4/lib/sibit/btc.rb:123:in `utxos'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#82` is not assigned, can't get performer
