### ISSUE TITLE
OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#99]
```
OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0
	/usr/local/rvm/gems/ruby-3.0.1/gems/bitcoin-ruby-0.0.20/lib/bitcoin/key.rb:264:in `private_key='
	/usr/local/rvm/gems/ruby-3.0.1/gems/bitcoin-ruby-0.0.20/lib/bitcoin/key.rb:264:in `set_priv'
	/usr/local/rvm/gems/ruby-3.0.1/gems/bitcoin-ruby-0.0.20/lib/bitcoin/key.rb:62:in `priv='
	/usr/local/rvm/gems/ruby-3.0.1/gems/sibit-0.23.0/lib/sibit.rb:289:in `key'
	/usr/local/rvm/gems/ruby-3.0.1/gems/sibit-0.23.0/lib/sibit.rb:132:in `block (2 levels) in pay'
	/usr/local/rvm/gems/ruby-3.0.1/gems/bitcoin-ruby-0.0.20/lib/bitcoin/builder.rb:158:in `input'
	/usr/local/rvm/gems/ruby-3.0.1/gems/sibit-0.23.0/lib/sibit.rb:127:in `block in pay'
	/usr/local/rvm/gems/ruby-3.0.1/gems/sibit-0.23.0/lib/sibit.rb:125:in `each'
	/usr/local/rvm/gems/ruby-3.0.1/gems/sibit-0.23.0/lib/sibit.rb:125:in `pay'
	/usr/local/rvm/gems/ruby-3.0.1/gems/sibit-0.23.0/bin/sibit:141:in `<top (required)>'
	/usr/local/rvm/gems/ruby-3.0.1/bin/sibit:23:in `load'
	/usr/local/rvm/gems/ruby-3.0.1/bin/sibit:23:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.1`
